### PR TITLE
Fix weather anomaly matviews refresh

### LINKED ISSUE #64: Weather anomaly matviews broken

### PR DESCRIPTION
**Pull request by rod-glover**
Resolves #64

### CODE REVIEW

**Comment by rod-glover** [comment]
After some investigation, I can see that the functions in question (`effective_day`, `daysinmonth`) are:
- defined identically in the CRMP database and in the test framework (actually, in the migration that creates the functions in the test databases), and I mean SQL line by line identical because copied directly
- invoked by the database engine with identical SQL (courtesy of database activity logging)

My only remaining hypothesis is that the disparity between behaviour in tests and the script lies in the difference between the 
- production database, which reports itself running `'PostgreSQL 9.1.13 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit'`) 
- test database, which reports itself `'PostgreSQL 9.5.23 on x86_64-pc-linux-gnu (Ubuntu 9.5.23-1.pgdg18.04+1), compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit'`.

Given that I understand our PostgreSQL 9.5 testing environment represents the best feasible approximation to 9.1, I am not going modify tests, and we will just have to live with this difference until the databases are moved to a more up to date server.

**Comment by rod-glover** [comment]
The modifications to the code fix the script error against production, and still pass tests.

**Comment by rod-glover** [comment]
@jameshiebert , I've asked for a code review from you, but only if you have time.

**Comment by rod-glover** [comment]
I'm also inclined to remove `dev.Dockerfile` and its associated main README content, because it has been superseded by the local-test Dockerfile and its documentation. The latter provide a pretty much identical environment to our CI test environment, which is desirable for activities like figuring out why code works in test but not in production. We want the fewest number of distinct environments possible; 2 is already 1 too many.

File: docker/local-test/entrypoint.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# Install PyCDS
+pip3 install -r requirements.txt -r test_requirements.txt
+pip3 install -e .
+
+# Use a non-root user so that Postgres doesn't object
+# Important: See README for reason user id 1000 is set here.
+useradd -u 1000 test
+chsh -s /bin/bash test
+su test
```
Comment (nikola-rados) [inline docker/local-test/entrypoint.sh:9]: I've had this same trouble with `postgres` before, such a hassle. Good work getting around it and I especially appreciate the documentation around the issue you've included.

File: docker/local-test/README.md [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+
+## Build image (manual)
+
+Since this image is built automatically by the GitHub Action docker-publish,
+you should not need to do this. However, just in case:
+
+From the _project root directory_ (important Docker context location):
+
+```
+docker build -t pycds-local-test -f docker/local-test/Dockerfile .
```
Comment (nikola-rados) [inline docker/local-test/README.md:112]: I don't know if this is an intentional difference, but the image name does not match the one we use from docker hub.

File: docker/local-test/README.md [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+leaves problematic pycache junk behind in the host filesystem. 
+This can be cleaned up by running `py3clean`.
+
+## Pull image
+
+The GitHub Action docker-publish automatically builds the image.
+Pull it from Dockerhub:
+
+```
+docker pull pcic/pycds:local-test
```
Comment (nikola-rados) [inline docker/local-test/README.md:84]: Is there any reason for us to keep the image produced by `dev.Dockerfile`? If not should we consider having this `local-test` image follow the typical docker naming convention? While the tag name works for now, the amount of overwriting that will be done may start to cause confusion.

**Review by nikola-rados — CHANGES_REQUESTED** [review]
We could merge this and it would be alright, but there is some room for changes. Namely, I think we should sort out what we are doing with the two different dockerfiles. That aside, I really appreciate the work you put in to document your findings and ideas :book:.

File: .github/workflows/docker-publish.yml [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    steps:
+      - uses: actions/checkout@master
+      - name: Publish to Registry
+        uses: docker/build-push-action@v1
+        with:
+          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
+          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
+          dockerfile: ./docker/local-test/Dockerfile
+          repository: pcic/pycds
+          tags: local-test
```
[the remark this answers is not in the document]
Comment (rod-glover) [reply .github/workflows/docker-publish.yml:40]: Argh, a bit of an oversight here on my part when you created the docker-publish action. Yes, I do want to remove `dev.Dockerfile`. I was thinking there was also a regular, "production" Dockerfile, which of course there is not because this is a library package, not an application.

We do need the local-test dockerfile etc., but it is only for establishing a test environment. Do you think we should, as I have seen in other repos, make the Dockerfile at the root of the project which is a link to the one in `docker/...`? I think that makes the most sense but I am happy to follow whatever practices you prefer.

File: docker/local-test/Dockerfile [hunk 5]
```diff
@@ -0,0 +1,34 @@
+FROM ubuntu:18.04
```
[the remark this answers is not in the document]
Comment (rod-glover) [reply docker/local-test/Dockerfile:1]: I'm using this image because it is (I *think*) the same base image that our CI environment uses, and that is what is needed here in this image. In `python-ci.yml` we have `runs-on: ubuntu-18.04`, which I am thinking would imply this. Do you know to the contrary?

File: docker/local-test/README.md (hunk 2 above)
Comment (rod-glover) [reply docker/local-test/README.md:112]: It was intended to be different from the automatically generated image name, but that's of dubious value.

File: docker/local-test/README.md (hunk 3 above)
Comment (rod-glover) [reply docker/local-test/README.md:84]: That makes total sense to me. I'll update the action and you can correct me on any mistakes I make.

Comment (rod-glover) [reply docker/local-test/README.md:84]: Actually I just realized, after *reading my own documentation* :brain: , that this dockerfile (a) still serves a useful purpose, and (b) that purpose is distinct from the purpose of the local-test dockerfile. So I will shuttle things around but we will still have two docker images. There's a naming issue here ... how do we resolve it?

Comment (nikola-rados) [reply docker/local-test/README.md:84]: I was actually going to address the overall image name. If I understand correctly, neither of these images are actually used to create an instance of the application (in the way that the p2a-v2-frontend image is used, for example). If that is in fact the case, I think using the pycds name is a bit disingenuous and a bit confusing (hence why I am confused haha). Therefore we can have two separate dockerhub repos for the two different images being created and they can both use the naming standard. Your image name suggestions sound great to me! I would just recommend that you move dev.dockerfile to its own folder in docker/.

Comment (rod-glover) [reply docker/local-test/README.md:84]: Can the two images be given different names? If so, I'd suggest `pcic/pycds-local-pytest` for the one, and `pcic/pycds-test-db` for the other, and let tagging be as usual. Is that possible?

File: .github/workflows/docker-publish.yml (hunk 4 above)
[the remark this answers is not in the document]
Comment (nikola-rados) [reply .github/workflows/docker-publish.yml:40]: That makes the most sense, moving it would be preferable!

File: docker/local-test/Dockerfile (hunk 5 above)
[the remark this answers is not in the document]
Comment (nikola-rados) [reply docker/local-test/Dockerfile:1]: No you have it right, I forgot that these images are for testing rather than for running.

File: docker/local-test/README.md (hunk 2 above)
Comment (nikola-rados) [reply docker/local-test/README.md:112]: That's fine!

File: docker/local-test/README.md (hunk 3 above)
Comment (nikola-rados) [reply docker/local-test/README.md:84]: That is possible, they would just live in different places on dockerhub.

Comment (rod-glover) [reply docker/local-test/README.md:84]: I think we are on exactly the same wavelength here. 

You do understand correctly; there is no application _per se_; this is a library package, primarily used by other applications. (Although I suppose the scripts in this package constitute an application. We could install it in a Dockerfile so that the scripts could be run from there, but that seems unnecessary.)

Also agree on moving the dev.Dockerfile into `docker/`.

I don't know how to establish the naming conventions we both agree on here, but I will do the rest of the work and let you tweak the docker-publish action accordingly.

Comment (nikola-rados) [reply docker/local-test/README.md:84]: This [line](https://github.com/pacificclimate/pycds/blob/i64-wa-matviews/.github/workflows/docker-publish.yml#L24) determines the image name. So you would place `pcic/pycds-test-db` there. `tag_with_ref` should be set to `true` and the tag naming will be taken care of by the action.

**Comment by rod-glover** [comment]
@nikola-rados , I think I've covered all the changes we decided on. Ready for another look over by you.

**Comment by rod-glover** [comment]
Faintly hilarious that the actual bug fix in this PR is 2 lines (4 with new spacing), and the remaining 300+ lines is the struggle to set up suitable test environments.

**Review by nikola-rados — APPROVED** [review]
This looks great @rod-glover!
